// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateGauge } from "./types/osmosis/incentives/tx";
import { MsgAddToGauge } from "./types/osmosis/incentives/tx";

import { Gauge as typeGauge} from "./types"
import { LockableDurationsInfo as typeLockableDurationsInfo} from "./types"
import { Params as typeParams} from "./types"

export { MsgCreateGauge, MsgAddToGauge };

type sendMsgCreateGaugeParams = {
  value: MsgCreateGauge,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddToGaugeParams = {
  value: MsgAddToGauge,
  fee?: StdFee,
  memo?: string
};


type msgCreateGaugeParams = {
  value: MsgCreateGauge,
};

type msgAddToGaugeParams = {
  value: MsgAddToGauge,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateGauge({ value, fee, memo }: sendMsgCreateGaugeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateGauge: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateGauge({ value: MsgCreateGauge.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateGauge: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddToGauge({ value, fee, memo }: sendMsgAddToGaugeParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddToGauge: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddToGauge({ value: MsgAddToGauge.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddToGauge: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateGauge({ value }: msgCreateGaugeParams): EncodeObject {
			try {
				return { typeUrl: "/osmosis.incentives.MsgCreateGauge", value: MsgCreateGauge.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateGauge: Could not create message: ' + e.message)
			}
		},
		
		msgAddToGauge({ value }: msgAddToGaugeParams): EncodeObject {
			try {
				return { typeUrl: "/osmosis.incentives.MsgAddToGauge", value: MsgAddToGauge.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddToGauge: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Gauge: getStructure(typeGauge.fromPartial({})),
						LockableDurationsInfo: getStructure(typeLockableDurationsInfo.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			OsmosisIncentives: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;