#pragma once

enum REQUESTPROCESSOR_ERROR_CODE {
    kRPSUCCESS = 0,
    kPOOL_INIT_ERROR = 1,
    kGRPCSERVICE_SETUP_ERROR = 2,
    kPEERCLIENT_INIT_ERROR = 3,
    kREMOTEATTESTATION_ERROR = 4,
    kBINDING_ERROR = 5,
    kCOMPLIANCE_PROOF_ERROR = 6,
};
