#!/bin/bash
# two-chainz creates two gaiad chains and configures the relayer to

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SPECY_DATA="$(pwd)/data"
RELAYER_DIR="$(dirname $SCRIPTDIR)"
RELAYER_CONF="$HOME/.relayer"

# Ensure specyd is installed
if ! [ -x "$(which specyd)" ]; then
  echo "Error: specyd is not installed. Try running 'make build-specy'" >&2
  exit 1
fi

# Display software version for testers
echo "SPECYD VERSION INFO:"
specyd version --long

# Ensure jq is installed
if [[ ! -x "$(which jq)" ]]; then
  echo "jq (a tool for parsing json in the command line) is required..."
  echo "https://stedolan.github.io/jq/download/"
  exit 1
fi

# Ensure user understands what will be deleted
if [[ -d $SPECY_DATA ]] && [[ ! "$1" == "skip" ]]; then
  read -p "$(basename $0) will delete \$(pwd)/data and \$HOME/.relayer folders. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

# Delete data from old runs
rm -rf $SPECY_DATA &> /dev/null
rm -rf $RELAYER_CONF &> /dev/null

# Stop existing gaiad processes
killall specyd &> /dev/null

set -e

chainid0=test-2
chainid1=test-1

echo "Generating specy configurations..."
mkdir -p $SPECY_DATA && cd $SPECY_DATA && cd ../
./scripts/one-chain specyd $chainid0 ./data 26657 26656 6060 9090 stake samoleans
./scripts/one-chain specyd $chainid1 ./data 16657 16656 6061 9091 stake samoleans

[ -f $SPECY_DATA/$chainid0.log ] && echo "$chainid0 initialized. Watch file $SPECY_DATA/$chainid0.log to see its execution."
[ -f $SPECY_DATA/$chainid1.log ] && echo "$chainid1 initialized. Watch file $SPECY_DATA/$chainid1.log to see its execution."

cd $RELAYER_DIR

echo ""
echo "Building Relayer..."
make -C ../../ install

pwd

echo ""
echo "Generating rly configurations..."
rly config init

echo ""
echo "Generating rly chains configurations..."
rly chains add-dir configs/chains

SEED0=$(jq -r '.mnemonic' $SPECY_DATA/test-2/key_seed.json)
SEED1=$(jq -r '.mnemonic' $SPECY_DATA/test-1/key_seed.json)
echo "Key $(rly keys restore test-2 testkey "$SEED0") imported from test-2 to relayer..."
echo "Key $(rly keys restore test-1 testkey "$SEED1") imported from test-1 to relayer..."

echo ""
echo "Generating rly paths configurations..."
rly paths add-dir configs/paths
