#pragma once

typedef enum LOCALATTESTATION_ERROR_CODE {
    kLA_SUCCESS = 0,
    kLA_INVALID_PARAMETER = 1,
    kLA_VALID_SESSION = 2,
    kLA_INVALID_SESSION = 3,
    kLA_ATTESTATION_ERROR = 4,
    kLA_ATTESTATION_SE_ERROR = 5,
    kLA_IPP_ERROR = 6,
    kLA_NO_AVAILABLE_SESSION_ERROR = 7,
    kLA_MALLOC_ERROR = 8,
    kLA_ERROR_TAG_MISMATCH = 9,
    kLA_OUT_BUFFER_LENGTH_ERROR = 10,
    kLA_INVALID_REQUEST_TYPE_ERROR = 11,
    kLA_INVALID_PARAMETER_ERROR = 12,
    kLA_ENCLAVE_TRUST_ERROR = 13,
    kLA_ENCRYPT_DECRYPT_ERROR = 14,
    kLA_DUPLICATE_SESSION = 15
} localattestation_status_t;

typedef uint32_t ATTESTATION_STATUS;