#pragma once

typedef enum BINDING_ERROR_CODE
{
    kBD_SUCCESS = 0,
    kBD_GET_BINDING_ERROR = 1,
    kBD_RESOLVER_BINDING_ERROR = 2,
    kBD_GET_RULE_ERROR = 3,
    kBD_PARSE_TRANSACTION_ERROR = 4,
    kBD_SERIALIZE_CPROOF_ERROR = 5,
    kBD_CHECK_RULE_ERROR = 6,
    kBD_PARSE_CHECK_RULE_OUTPUT_ERROR = 7,
    kBD_SIGN_ERROR = 8,
    kBD_PARSE_TXINFO_ERROR = 9,
    kBD_SERIALIZE_REQUEST_ERROR = 10,
    kBD_SERIALIZE_RESPONSE_ERROR = 11,
    kBD_PARSE_REQUEST_ERROR = 12,
    kBD_PARSE_RESPONSE_ERROR = 13,

    kBD_SERIALIZE_TXINFO_ERROR = 14,
    kBD_ECALL_PROCESS_CPROOF_ERROR = 15,
    kBD_PARSE_CPROOF_STRING_ERROR = 16,
    kBD_MALLOC_ERROR = 17
} binding_status_t;
