// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Register.proto
#ifndef GRPC_Register_2eproto__INCLUDED
#define GRPC_Register_2eproto__INCLUDED

#include "Register.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace request_proto {

class Register final {
 public:
  static constexpr char const* service_full_name() {
    return "request_proto.Register";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::request_proto::EngineInfoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>> AsyncGetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>>(AsyncGetEngineInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>> PrepareAsyncGetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>>(PrepareAsyncGetEngineInfoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>* AsyncGetEngineInfoRaw(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::request_proto::EngineInfoResponse>* PrepareAsyncGetEngineInfoRaw(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::request_proto::EngineInfoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>> AsyncGetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>>(AsyncGetEngineInfoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>> PrepareAsyncGetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>>(PrepareAsyncGetEngineInfoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetEngineInfo(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>* AsyncGetEngineInfoRaw(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::request_proto::EngineInfoResponse>* PrepareAsyncGetEngineInfoRaw(::grpc::ClientContext* context, const ::request_proto::EngineInfoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetEngineInfo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetEngineInfo(::grpc::ServerContext* context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetEngineInfo() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEngineInfo(::grpc::ServerContext* context, ::request_proto::EngineInfoRequest* request, ::grpc::ServerAsyncResponseWriter< ::request_proto::EngineInfoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetEngineInfo<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetEngineInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::request_proto::EngineInfoRequest, ::request_proto::EngineInfoResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::request_proto::EngineInfoRequest* request, ::request_proto::EngineInfoResponse* response) { return this->GetEngineInfo(context, request, response); }));}
    void SetMessageAllocatorFor_GetEngineInfo(
        ::grpc::experimental::MessageAllocator< ::request_proto::EngineInfoRequest, ::request_proto::EngineInfoResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::request_proto::EngineInfoRequest, ::request_proto::EngineInfoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetEngineInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetEngineInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetEngineInfo<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetEngineInfo<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetEngineInfo() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetEngineInfo() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetEngineInfo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetEngineInfo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetEngineInfo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetEngineInfo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetEngineInfo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetEngineInfo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetEngineInfo() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::request_proto::EngineInfoRequest, ::request_proto::EngineInfoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::request_proto::EngineInfoRequest, ::request_proto::EngineInfoResponse>* streamer) {
                       return this->StreamedGetEngineInfo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetEngineInfo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetEngineInfo(::grpc::ServerContext* /*context*/, const ::request_proto::EngineInfoRequest* /*request*/, ::request_proto::EngineInfoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetEngineInfo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::request_proto::EngineInfoRequest,::request_proto::EngineInfoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetEngineInfo<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetEngineInfo<Service > StreamedService;
};

}  // namespace request_proto


#endif  // GRPC_Register_2eproto__INCLUDED
