// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateClawbackVestingAccount } from "./types/cosmos/vesting/v1beta1/tx";
import { MsgCreateVestingAccount } from "./types/cosmos/vesting/v1beta1/tx";
import { MsgClawback } from "./types/cosmos/vesting/v1beta1/tx";

import { BaseVestingAccount as typeBaseVestingAccount} from "./types"
import { ContinuousVestingAccount as typeContinuousVestingAccount} from "./types"
import { DelayedVestingAccount as typeDelayedVestingAccount} from "./types"
import { Period as typePeriod} from "./types"
import { PeriodicVestingAccount as typePeriodicVestingAccount} from "./types"
import { PermanentLockedAccount as typePermanentLockedAccount} from "./types"
import { ClawbackVestingAccount as typeClawbackVestingAccount} from "./types"

export { MsgCreateClawbackVestingAccount, MsgCreateVestingAccount, MsgClawback };

type sendMsgCreateClawbackVestingAccountParams = {
  value: MsgCreateClawbackVestingAccount,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateVestingAccountParams = {
  value: MsgCreateVestingAccount,
  fee?: StdFee,
  memo?: string
};

type sendMsgClawbackParams = {
  value: MsgClawback,
  fee?: StdFee,
  memo?: string
};


type msgCreateClawbackVestingAccountParams = {
  value: MsgCreateClawbackVestingAccount,
};

type msgCreateVestingAccountParams = {
  value: MsgCreateVestingAccount,
};

type msgClawbackParams = {
  value: MsgClawback,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateClawbackVestingAccount({ value, fee, memo }: sendMsgCreateClawbackVestingAccountParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateClawbackVestingAccount: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateClawbackVestingAccount({ value: MsgCreateClawbackVestingAccount.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateClawbackVestingAccount: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateVestingAccount({ value, fee, memo }: sendMsgCreateVestingAccountParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateVestingAccount: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateVestingAccount({ value: MsgCreateVestingAccount.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateVestingAccount: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgClawback({ value, fee, memo }: sendMsgClawbackParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgClawback: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgClawback({ value: MsgClawback.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgClawback: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateClawbackVestingAccount({ value }: msgCreateClawbackVestingAccountParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.vesting.v1beta1.MsgCreateClawbackVestingAccount", value: MsgCreateClawbackVestingAccount.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateClawbackVestingAccount: Could not create message: ' + e.message)
			}
		},
		
		msgCreateVestingAccount({ value }: msgCreateVestingAccountParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.vesting.v1beta1.MsgCreateVestingAccount", value: MsgCreateVestingAccount.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateVestingAccount: Could not create message: ' + e.message)
			}
		},
		
		msgClawback({ value }: msgClawbackParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.vesting.v1beta1.MsgClawback", value: MsgClawback.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgClawback: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						BaseVestingAccount: getStructure(typeBaseVestingAccount.fromPartial({})),
						ContinuousVestingAccount: getStructure(typeContinuousVestingAccount.fromPartial({})),
						DelayedVestingAccount: getStructure(typeDelayedVestingAccount.fromPartial({})),
						Period: getStructure(typePeriod.fromPartial({})),
						PeriodicVestingAccount: getStructure(typePeriodicVestingAccount.fromPartial({})),
						PermanentLockedAccount: getStructure(typePermanentLockedAccount.fromPartial({})),
						ClawbackVestingAccount: getStructure(typeClawbackVestingAccount.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			CosmosVestingV1Beta1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;