// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BindingQuery.proto

#include "BindingQuery.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_BindingQuery_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BindingQueryItem_BindingQuery_2eproto;
namespace request_proto {
class BindingQueryItemDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BindingQueryItem> _instance;
} _BindingQueryItem_default_instance_;
class BindingQueryMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BindingQueryMessage> _instance;
} _BindingQueryMessage_default_instance_;
}  // namespace request_proto
static void InitDefaultsBindingQueryItem_BindingQuery_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::request_proto::_BindingQueryItem_default_instance_;
    new (ptr) ::request_proto::BindingQueryItem();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::request_proto::BindingQueryItem::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BindingQueryItem_BindingQuery_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBindingQueryItem_BindingQuery_2eproto}, {}};

static void InitDefaultsBindingQueryMessage_BindingQuery_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::request_proto::_BindingQueryMessage_default_instance_;
    new (ptr) ::request_proto::BindingQueryMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::request_proto::BindingQueryMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_BindingQueryMessage_BindingQuery_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBindingQueryMessage_BindingQuery_2eproto}, {
      &scc_info_BindingQueryItem_BindingQuery_2eproto.base,}};

void InitDefaults_BindingQuery_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_BindingQueryItem_BindingQuery_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BindingQueryMessage_BindingQuery_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_BindingQuery_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_BindingQuery_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_BindingQuery_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_BindingQuery_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::request_proto::BindingQueryItem, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::request_proto::BindingQueryItem, contractid_),
  PROTOBUF_FIELD_OFFSET(::request_proto::BindingQueryItem, contractbinding_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::request_proto::BindingQueryMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::request_proto::BindingQueryMessage, items_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::request_proto::BindingQueryItem)},
  { 7, -1, sizeof(::request_proto::BindingQueryMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::request_proto::_BindingQueryItem_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::request_proto::_BindingQueryMessage_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_BindingQuery_2eproto = {
  {}, AddDescriptors_BindingQuery_2eproto, "BindingQuery.proto", schemas,
  file_default_instances, TableStruct_BindingQuery_2eproto::offsets,
  file_level_metadata_BindingQuery_2eproto, 2, file_level_enum_descriptors_BindingQuery_2eproto, file_level_service_descriptors_BindingQuery_2eproto,
};

const char descriptor_table_protodef_BindingQuery_2eproto[] =
  "\n\022BindingQuery.proto\022\rrequest_proto\"\?\n\020B"
  "indingQueryItem\022\022\n\ncontractID\030\001 \001(\t\022\027\n\017c"
  "ontractBinding\030\002 \001(\t\"E\n\023BindingQueryMess"
  "age\022.\n\005items\030\001 \003(\0132\037.request_proto.Bindi"
  "ngQueryItemb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_BindingQuery_2eproto = {
  false, InitDefaults_BindingQuery_2eproto, 
  descriptor_table_protodef_BindingQuery_2eproto,
  "BindingQuery.proto", &assign_descriptors_table_BindingQuery_2eproto, 179,
};

void AddDescriptors_BindingQuery_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_BindingQuery_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_BindingQuery_2eproto = []() { AddDescriptors_BindingQuery_2eproto(); return true; }();
namespace request_proto {

// ===================================================================

void BindingQueryItem::InitAsDefaultInstance() {
}
class BindingQueryItem::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BindingQueryItem::kContractIDFieldNumber;
const int BindingQueryItem::kContractBindingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BindingQueryItem::BindingQueryItem()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:request_proto.BindingQueryItem)
}
BindingQueryItem::BindingQueryItem(const BindingQueryItem& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  contractid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.contractid().size() > 0) {
    contractid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.contractid_);
  }
  contractbinding_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.contractbinding().size() > 0) {
    contractbinding_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.contractbinding_);
  }
  // @@protoc_insertion_point(copy_constructor:request_proto.BindingQueryItem)
}

void BindingQueryItem::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_BindingQueryItem_BindingQuery_2eproto.base);
  contractid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  contractbinding_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

BindingQueryItem::~BindingQueryItem() {
  // @@protoc_insertion_point(destructor:request_proto.BindingQueryItem)
  SharedDtor();
}

void BindingQueryItem::SharedDtor() {
  contractid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  contractbinding_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BindingQueryItem::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BindingQueryItem& BindingQueryItem::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_BindingQueryItem_BindingQuery_2eproto.base);
  return *internal_default_instance();
}


void BindingQueryItem::Clear() {
// @@protoc_insertion_point(message_clear_start:request_proto.BindingQueryItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  contractid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  contractbinding_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* BindingQueryItem::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<BindingQueryItem*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string contractID = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("request_proto.BindingQueryItem.contractID");
        object = msg->mutable_contractid();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string contractBinding = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("request_proto.BindingQueryItem.contractBinding");
        object = msg->mutable_contractbinding();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool BindingQueryItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:request_proto.BindingQueryItem)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string contractID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_contractid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->contractid().data(), static_cast<int>(this->contractid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_proto.BindingQueryItem.contractID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string contractBinding = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_contractbinding()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->contractbinding().data(), static_cast<int>(this->contractbinding().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "request_proto.BindingQueryItem.contractBinding"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:request_proto.BindingQueryItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:request_proto.BindingQueryItem)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void BindingQueryItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:request_proto.BindingQueryItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string contractID = 1;
  if (this->contractid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->contractid().data(), static_cast<int>(this->contractid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_proto.BindingQueryItem.contractID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->contractid(), output);
  }

  // string contractBinding = 2;
  if (this->contractbinding().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->contractbinding().data(), static_cast<int>(this->contractbinding().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_proto.BindingQueryItem.contractBinding");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->contractbinding(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:request_proto.BindingQueryItem)
}

::google::protobuf::uint8* BindingQueryItem::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:request_proto.BindingQueryItem)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string contractID = 1;
  if (this->contractid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->contractid().data(), static_cast<int>(this->contractid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_proto.BindingQueryItem.contractID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->contractid(), target);
  }

  // string contractBinding = 2;
  if (this->contractbinding().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->contractbinding().data(), static_cast<int>(this->contractbinding().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "request_proto.BindingQueryItem.contractBinding");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->contractbinding(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:request_proto.BindingQueryItem)
  return target;
}

size_t BindingQueryItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:request_proto.BindingQueryItem)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string contractID = 1;
  if (this->contractid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->contractid());
  }

  // string contractBinding = 2;
  if (this->contractbinding().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->contractbinding());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BindingQueryItem::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:request_proto.BindingQueryItem)
  GOOGLE_DCHECK_NE(&from, this);
  const BindingQueryItem* source =
      ::google::protobuf::DynamicCastToGenerated<BindingQueryItem>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:request_proto.BindingQueryItem)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:request_proto.BindingQueryItem)
    MergeFrom(*source);
  }
}

void BindingQueryItem::MergeFrom(const BindingQueryItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:request_proto.BindingQueryItem)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.contractid().size() > 0) {

    contractid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.contractid_);
  }
  if (from.contractbinding().size() > 0) {

    contractbinding_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.contractbinding_);
  }
}

void BindingQueryItem::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:request_proto.BindingQueryItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BindingQueryItem::CopyFrom(const BindingQueryItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:request_proto.BindingQueryItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BindingQueryItem::IsInitialized() const {
  return true;
}

void BindingQueryItem::Swap(BindingQueryItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BindingQueryItem::InternalSwap(BindingQueryItem* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  contractid_.Swap(&other->contractid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  contractbinding_.Swap(&other->contractbinding_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata BindingQueryItem::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BindingQuery_2eproto);
  return ::file_level_metadata_BindingQuery_2eproto[kIndexInFileMessages];
}


// ===================================================================

void BindingQueryMessage::InitAsDefaultInstance() {
}
class BindingQueryMessage::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BindingQueryMessage::kItemsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BindingQueryMessage::BindingQueryMessage()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:request_proto.BindingQueryMessage)
}
BindingQueryMessage::BindingQueryMessage(const BindingQueryMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      items_(from.items_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:request_proto.BindingQueryMessage)
}

void BindingQueryMessage::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_BindingQueryMessage_BindingQuery_2eproto.base);
}

BindingQueryMessage::~BindingQueryMessage() {
  // @@protoc_insertion_point(destructor:request_proto.BindingQueryMessage)
  SharedDtor();
}

void BindingQueryMessage::SharedDtor() {
}

void BindingQueryMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BindingQueryMessage& BindingQueryMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_BindingQueryMessage_BindingQuery_2eproto.base);
  return *internal_default_instance();
}


void BindingQueryMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:request_proto.BindingQueryMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  items_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* BindingQueryMessage::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<BindingQueryMessage*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .request_proto.BindingQueryItem items = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::request_proto::BindingQueryItem::_InternalParse;
          object = msg->add_items();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool BindingQueryMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:request_proto.BindingQueryMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .request_proto.BindingQueryItem items = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_items()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:request_proto.BindingQueryMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:request_proto.BindingQueryMessage)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void BindingQueryMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:request_proto.BindingQueryMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .request_proto.BindingQueryItem items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->items(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:request_proto.BindingQueryMessage)
}

::google::protobuf::uint8* BindingQueryMessage::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:request_proto.BindingQueryMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .request_proto.BindingQueryItem items = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->items_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->items(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:request_proto.BindingQueryMessage)
  return target;
}

size_t BindingQueryMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:request_proto.BindingQueryMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .request_proto.BindingQueryItem items = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->items_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->items(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BindingQueryMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:request_proto.BindingQueryMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const BindingQueryMessage* source =
      ::google::protobuf::DynamicCastToGenerated<BindingQueryMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:request_proto.BindingQueryMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:request_proto.BindingQueryMessage)
    MergeFrom(*source);
  }
}

void BindingQueryMessage::MergeFrom(const BindingQueryMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:request_proto.BindingQueryMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  items_.MergeFrom(from.items_);
}

void BindingQueryMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:request_proto.BindingQueryMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BindingQueryMessage::CopyFrom(const BindingQueryMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:request_proto.BindingQueryMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BindingQueryMessage::IsInitialized() const {
  return true;
}

void BindingQueryMessage::Swap(BindingQueryMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BindingQueryMessage::InternalSwap(BindingQueryMessage* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&items_)->InternalSwap(CastToBase(&other->items_));
}

::google::protobuf::Metadata BindingQueryMessage::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_BindingQuery_2eproto);
  return ::file_level_metadata_BindingQuery_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace request_proto
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::request_proto::BindingQueryItem* Arena::CreateMaybeMessage< ::request_proto::BindingQueryItem >(Arena* arena) {
  return Arena::CreateInternal< ::request_proto::BindingQueryItem >(arena);
}
template<> PROTOBUF_NOINLINE ::request_proto::BindingQueryMessage* Arena::CreateMaybeMessage< ::request_proto::BindingQueryMessage >(Arena* arena) {
  return Arena::CreateInternal< ::request_proto::BindingQueryMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
