// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgCreateStableswapPool } from "./types/osmosis/gamm/pool-models/stableswap/tx";
import { MsgStableSwapAdjustScalingFactors } from "./types/osmosis/gamm/pool-models/stableswap/tx";

import { PoolParams as typePoolParams} from "./types"
import { Pool as typePool} from "./types"

export { MsgCreateStableswapPool, MsgStableSwapAdjustScalingFactors };

type sendMsgCreateStableswapPoolParams = {
  value: MsgCreateStableswapPool,
  fee?: StdFee,
  memo?: string
};

type sendMsgStableSwapAdjustScalingFactorsParams = {
  value: MsgStableSwapAdjustScalingFactors,
  fee?: StdFee,
  memo?: string
};


type msgCreateStableswapPoolParams = {
  value: MsgCreateStableswapPool,
};

type msgStableSwapAdjustScalingFactorsParams = {
  value: MsgStableSwapAdjustScalingFactors,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgCreateStableswapPool({ value, fee, memo }: sendMsgCreateStableswapPoolParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateStableswapPool: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateStableswapPool({ value: MsgCreateStableswapPool.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateStableswapPool: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStableSwapAdjustScalingFactors({ value, fee, memo }: sendMsgStableSwapAdjustScalingFactorsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStableSwapAdjustScalingFactors: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgStableSwapAdjustScalingFactors({ value: MsgStableSwapAdjustScalingFactors.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStableSwapAdjustScalingFactors: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgCreateStableswapPool({ value }: msgCreateStableswapPoolParams): EncodeObject {
			try {
				return { typeUrl: "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgCreateStableswapPool", value: MsgCreateStableswapPool.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateStableswapPool: Could not create message: ' + e.message)
			}
		},
		
		msgStableSwapAdjustScalingFactors({ value }: msgStableSwapAdjustScalingFactorsParams): EncodeObject {
			try {
				return { typeUrl: "/osmosis.gamm.poolmodels.stableswap.v1beta1.MsgStableSwapAdjustScalingFactors", value: MsgStableSwapAdjustScalingFactors.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStableSwapAdjustScalingFactors: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						PoolParams: getStructure(typePoolParams.fromPartial({})),
						Pool: getStructure(typePool.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			OsmosisGammPoolmodelsStableswapV1Beta1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;