// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RuleCheck.proto

#include "RuleCheck.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace e2e_message {
class RuleCheckRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RuleCheckRequest> _instance;
} _RuleCheckRequest_default_instance_;
class RuleCheckResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RuleCheckResponse> _instance;
} _RuleCheckResponse_default_instance_;
}  // namespace e2e_message
static void InitDefaultsRuleCheckRequest_RuleCheck_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e2e_message::_RuleCheckRequest_default_instance_;
    new (ptr) ::e2e_message::RuleCheckRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e2e_message::RuleCheckRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RuleCheckRequest_RuleCheck_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRuleCheckRequest_RuleCheck_2eproto}, {}};

static void InitDefaultsRuleCheckResponse_RuleCheck_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::e2e_message::_RuleCheckResponse_default_instance_;
    new (ptr) ::e2e_message::RuleCheckResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::e2e_message::RuleCheckResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RuleCheckResponse_RuleCheck_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRuleCheckResponse_RuleCheck_2eproto}, {}};

void InitDefaults_RuleCheck_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_RuleCheckRequest_RuleCheck_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_RuleCheckResponse_RuleCheck_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_RuleCheck_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_RuleCheck_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_RuleCheck_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_RuleCheck_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckRequest, taskhash_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckRequest, rule_file_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckRequest, input_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, taskhash_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, status_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, error_info_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, output_data_),
  PROTOBUF_FIELD_OFFSET(::e2e_message::RuleCheckResponse, cproof_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::e2e_message::RuleCheckRequest)},
  { 8, -1, sizeof(::e2e_message::RuleCheckResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::e2e_message::_RuleCheckRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::e2e_message::_RuleCheckResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_RuleCheck_2eproto = {
  {}, AddDescriptors_RuleCheck_2eproto, "RuleCheck.proto", schemas,
  file_default_instances, TableStruct_RuleCheck_2eproto::offsets,
  file_level_metadata_RuleCheck_2eproto, 2, file_level_enum_descriptors_RuleCheck_2eproto, file_level_service_descriptors_RuleCheck_2eproto,
};

const char descriptor_table_protodef_RuleCheck_2eproto[] =
  "\n\017RuleCheck.proto\022\013e2e_message\"K\n\020RuleCh"
  "eckRequest\022\020\n\010taskhash\030\001 \001(\014\022\021\n\trule_fil"
  "e\030\002 \001(\t\022\022\n\ninput_data\030\003 \001(\t\"n\n\021RuleCheck"
  "Response\022\020\n\010taskhash\030\001 \001(\014\022\016\n\006status\030\002 \001"
  "(\010\022\022\n\nerror_info\030\003 \001(\t\022\023\n\013output_data\030\004 "
  "\001(\t\022\016\n\006cproof\030\005 \001(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_RuleCheck_2eproto = {
  false, InitDefaults_RuleCheck_2eproto, 
  descriptor_table_protodef_RuleCheck_2eproto,
  "RuleCheck.proto", &assign_descriptors_table_RuleCheck_2eproto, 227,
};

void AddDescriptors_RuleCheck_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_RuleCheck_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_RuleCheck_2eproto = []() { AddDescriptors_RuleCheck_2eproto(); return true; }();
namespace e2e_message {

// ===================================================================

void RuleCheckRequest::InitAsDefaultInstance() {
}
class RuleCheckRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RuleCheckRequest::kTaskhashFieldNumber;
const int RuleCheckRequest::kRuleFileFieldNumber;
const int RuleCheckRequest::kInputDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RuleCheckRequest::RuleCheckRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:e2e_message.RuleCheckRequest)
}
RuleCheckRequest::RuleCheckRequest(const RuleCheckRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  taskhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.taskhash().size() > 0) {
    taskhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.taskhash_);
  }
  rule_file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.rule_file().size() > 0) {
    rule_file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rule_file_);
  }
  input_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.input_data().size() > 0) {
    input_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.input_data_);
  }
  // @@protoc_insertion_point(copy_constructor:e2e_message.RuleCheckRequest)
}

void RuleCheckRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_RuleCheckRequest_RuleCheck_2eproto.base);
  taskhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rule_file_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  input_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

RuleCheckRequest::~RuleCheckRequest() {
  // @@protoc_insertion_point(destructor:e2e_message.RuleCheckRequest)
  SharedDtor();
}

void RuleCheckRequest::SharedDtor() {
  taskhash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rule_file_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  input_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RuleCheckRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RuleCheckRequest& RuleCheckRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_RuleCheckRequest_RuleCheck_2eproto.base);
  return *internal_default_instance();
}


void RuleCheckRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:e2e_message.RuleCheckRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  taskhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  rule_file_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  input_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* RuleCheckRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<RuleCheckRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes taskhash = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_taskhash();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string rule_file = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("e2e_message.RuleCheckRequest.rule_file");
        object = msg->mutable_rule_file();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string input_data = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("e2e_message.RuleCheckRequest.input_data");
        object = msg->mutable_input_data();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool RuleCheckRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e2e_message.RuleCheckRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes taskhash = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_taskhash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string rule_file = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_rule_file()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->rule_file().data(), static_cast<int>(this->rule_file().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e2e_message.RuleCheckRequest.rule_file"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string input_data = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_input_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->input_data().data(), static_cast<int>(this->input_data().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e2e_message.RuleCheckRequest.input_data"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e2e_message.RuleCheckRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e2e_message.RuleCheckRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void RuleCheckRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e2e_message.RuleCheckRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->taskhash(), output);
  }

  // string rule_file = 2;
  if (this->rule_file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->rule_file().data(), static_cast<int>(this->rule_file().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckRequest.rule_file");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->rule_file(), output);
  }

  // string input_data = 3;
  if (this->input_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->input_data().data(), static_cast<int>(this->input_data().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckRequest.input_data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->input_data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:e2e_message.RuleCheckRequest)
}

::google::protobuf::uint8* RuleCheckRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:e2e_message.RuleCheckRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->taskhash(), target);
  }

  // string rule_file = 2;
  if (this->rule_file().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->rule_file().data(), static_cast<int>(this->rule_file().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckRequest.rule_file");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->rule_file(), target);
  }

  // string input_data = 3;
  if (this->input_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->input_data().data(), static_cast<int>(this->input_data().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckRequest.input_data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->input_data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e2e_message.RuleCheckRequest)
  return target;
}

size_t RuleCheckRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e2e_message.RuleCheckRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->taskhash());
  }

  // string rule_file = 2;
  if (this->rule_file().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->rule_file());
  }

  // string input_data = 3;
  if (this->input_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->input_data());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RuleCheckRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e2e_message.RuleCheckRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const RuleCheckRequest* source =
      ::google::protobuf::DynamicCastToGenerated<RuleCheckRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e2e_message.RuleCheckRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e2e_message.RuleCheckRequest)
    MergeFrom(*source);
  }
}

void RuleCheckRequest::MergeFrom(const RuleCheckRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e2e_message.RuleCheckRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.taskhash().size() > 0) {

    taskhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.taskhash_);
  }
  if (from.rule_file().size() > 0) {

    rule_file_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.rule_file_);
  }
  if (from.input_data().size() > 0) {

    input_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.input_data_);
  }
}

void RuleCheckRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e2e_message.RuleCheckRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RuleCheckRequest::CopyFrom(const RuleCheckRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e2e_message.RuleCheckRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RuleCheckRequest::IsInitialized() const {
  return true;
}

void RuleCheckRequest::Swap(RuleCheckRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RuleCheckRequest::InternalSwap(RuleCheckRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  taskhash_.Swap(&other->taskhash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  rule_file_.Swap(&other->rule_file_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  input_data_.Swap(&other->input_data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata RuleCheckRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_RuleCheck_2eproto);
  return ::file_level_metadata_RuleCheck_2eproto[kIndexInFileMessages];
}


// ===================================================================

void RuleCheckResponse::InitAsDefaultInstance() {
}
class RuleCheckResponse::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RuleCheckResponse::kTaskhashFieldNumber;
const int RuleCheckResponse::kStatusFieldNumber;
const int RuleCheckResponse::kErrorInfoFieldNumber;
const int RuleCheckResponse::kOutputDataFieldNumber;
const int RuleCheckResponse::kCproofFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RuleCheckResponse::RuleCheckResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:e2e_message.RuleCheckResponse)
}
RuleCheckResponse::RuleCheckResponse(const RuleCheckResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  taskhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.taskhash().size() > 0) {
    taskhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.taskhash_);
  }
  error_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.error_info().size() > 0) {
    error_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_info_);
  }
  output_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.output_data().size() > 0) {
    output_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_data_);
  }
  cproof_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cproof().size() > 0) {
    cproof_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cproof_);
  }
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:e2e_message.RuleCheckResponse)
}

void RuleCheckResponse::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_RuleCheckResponse_RuleCheck_2eproto.base);
  taskhash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  output_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cproof_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = false;
}

RuleCheckResponse::~RuleCheckResponse() {
  // @@protoc_insertion_point(destructor:e2e_message.RuleCheckResponse)
  SharedDtor();
}

void RuleCheckResponse::SharedDtor() {
  taskhash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  output_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cproof_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RuleCheckResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RuleCheckResponse& RuleCheckResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_RuleCheckResponse_RuleCheck_2eproto.base);
  return *internal_default_instance();
}


void RuleCheckResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:e2e_message.RuleCheckResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  taskhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  error_info_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  output_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cproof_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = false;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* RuleCheckResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<RuleCheckResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes taskhash = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_taskhash();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // bool status = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_status(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string error_info = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("e2e_message.RuleCheckResponse.error_info");
        object = msg->mutable_error_info();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string output_data = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("e2e_message.RuleCheckResponse.output_data");
        object = msg->mutable_output_data();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string cproof = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 42) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("e2e_message.RuleCheckResponse.cproof");
        object = msg->mutable_cproof();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool RuleCheckResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:e2e_message.RuleCheckResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes taskhash = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_taskhash()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool status = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &status_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string error_info = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error_info()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->error_info().data(), static_cast<int>(this->error_info().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e2e_message.RuleCheckResponse.error_info"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string output_data = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_output_data()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->output_data().data(), static_cast<int>(this->output_data().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e2e_message.RuleCheckResponse.output_data"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cproof = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cproof()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cproof().data(), static_cast<int>(this->cproof().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "e2e_message.RuleCheckResponse.cproof"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:e2e_message.RuleCheckResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:e2e_message.RuleCheckResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void RuleCheckResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:e2e_message.RuleCheckResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->taskhash(), output);
  }

  // bool status = 2;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->status(), output);
  }

  // string error_info = 3;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), static_cast<int>(this->error_info().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.error_info");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->error_info(), output);
  }

  // string output_data = 4;
  if (this->output_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output_data().data(), static_cast<int>(this->output_data().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.output_data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->output_data(), output);
  }

  // string cproof = 5;
  if (this->cproof().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cproof().data(), static_cast<int>(this->cproof().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.cproof");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->cproof(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:e2e_message.RuleCheckResponse)
}

::google::protobuf::uint8* RuleCheckResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:e2e_message.RuleCheckResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->taskhash(), target);
  }

  // bool status = 2;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->status(), target);
  }

  // string error_info = 3;
  if (this->error_info().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error_info().data(), static_cast<int>(this->error_info().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.error_info");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->error_info(), target);
  }

  // string output_data = 4;
  if (this->output_data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->output_data().data(), static_cast<int>(this->output_data().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.output_data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->output_data(), target);
  }

  // string cproof = 5;
  if (this->cproof().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cproof().data(), static_cast<int>(this->cproof().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "e2e_message.RuleCheckResponse.cproof");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->cproof(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:e2e_message.RuleCheckResponse)
  return target;
}

size_t RuleCheckResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:e2e_message.RuleCheckResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes taskhash = 1;
  if (this->taskhash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->taskhash());
  }

  // string error_info = 3;
  if (this->error_info().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->error_info());
  }

  // string output_data = 4;
  if (this->output_data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->output_data());
  }

  // string cproof = 5;
  if (this->cproof().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cproof());
  }

  // bool status = 2;
  if (this->status() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RuleCheckResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:e2e_message.RuleCheckResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const RuleCheckResponse* source =
      ::google::protobuf::DynamicCastToGenerated<RuleCheckResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:e2e_message.RuleCheckResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:e2e_message.RuleCheckResponse)
    MergeFrom(*source);
  }
}

void RuleCheckResponse::MergeFrom(const RuleCheckResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:e2e_message.RuleCheckResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.taskhash().size() > 0) {

    taskhash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.taskhash_);
  }
  if (from.error_info().size() > 0) {

    error_info_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_info_);
  }
  if (from.output_data().size() > 0) {

    output_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.output_data_);
  }
  if (from.cproof().size() > 0) {

    cproof_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cproof_);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void RuleCheckResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:e2e_message.RuleCheckResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RuleCheckResponse::CopyFrom(const RuleCheckResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:e2e_message.RuleCheckResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RuleCheckResponse::IsInitialized() const {
  return true;
}

void RuleCheckResponse::Swap(RuleCheckResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RuleCheckResponse::InternalSwap(RuleCheckResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  taskhash_.Swap(&other->taskhash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  error_info_.Swap(&other->error_info_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  output_data_.Swap(&other->output_data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  cproof_.Swap(&other->cproof_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(status_, other->status_);
}

::google::protobuf::Metadata RuleCheckResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_RuleCheck_2eproto);
  return ::file_level_metadata_RuleCheck_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace e2e_message
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::e2e_message::RuleCheckRequest* Arena::CreateMaybeMessage< ::e2e_message::RuleCheckRequest >(Arena* arena) {
  return Arena::CreateInternal< ::e2e_message::RuleCheckRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::e2e_message::RuleCheckResponse* Arena::CreateMaybeMessage< ::e2e_message::RuleCheckResponse >(Arena* arena) {
  return Arena::CreateInternal< ::e2e_message::RuleCheckResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
