// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Signature.proto

#ifndef PROTOBUF_INCLUDED_Signature_2eproto
#define PROTOBUF_INCLUDED_Signature_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Signature_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_Signature_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_Signature_2eproto();
namespace e2e_message {
class SignInput;
class SignInputDefaultTypeInternal;
extern SignInputDefaultTypeInternal _SignInput_default_instance_;
class SignOutput;
class SignOutputDefaultTypeInternal;
extern SignOutputDefaultTypeInternal _SignOutput_default_instance_;
}  // namespace e2e_message
namespace google {
namespace protobuf {
template<> ::e2e_message::SignInput* Arena::CreateMaybeMessage<::e2e_message::SignInput>(Arena*);
template<> ::e2e_message::SignOutput* Arena::CreateMaybeMessage<::e2e_message::SignOutput>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace e2e_message {

// ===================================================================

class SignInput :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:e2e_message.SignInput) */ {
 public:
  SignInput();
  virtual ~SignInput();

  SignInput(const SignInput& from);

  inline SignInput& operator=(const SignInput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SignInput(SignInput&& from) noexcept
    : SignInput() {
    *this = ::std::move(from);
  }

  inline SignInput& operator=(SignInput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SignInput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SignInput* internal_default_instance() {
    return reinterpret_cast<const SignInput*>(
               &_SignInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SignInput* other);
  friend void swap(SignInput& a, SignInput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SignInput* New() const final {
    return CreateMaybeMessage<SignInput>(nullptr);
  }

  SignInput* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SignInput>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SignInput& from);
  void MergeFrom(const SignInput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignInput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string datas = 1;
  void clear_datas();
  static const int kDatasFieldNumber = 1;
  const ::std::string& datas() const;
  void set_datas(const ::std::string& value);
  #if LANG_CXX11
  void set_datas(::std::string&& value);
  #endif
  void set_datas(const char* value);
  void set_datas(const char* value, size_t size);
  ::std::string* mutable_datas();
  ::std::string* release_datas();
  void set_allocated_datas(::std::string* datas);

  // @@protoc_insertion_point(class_scope:e2e_message.SignInput)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr datas_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Signature_2eproto;
};
// -------------------------------------------------------------------

class SignOutput :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:e2e_message.SignOutput) */ {
 public:
  SignOutput();
  virtual ~SignOutput();

  SignOutput(const SignOutput& from);

  inline SignOutput& operator=(const SignOutput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SignOutput(SignOutput&& from) noexcept
    : SignOutput() {
    *this = ::std::move(from);
  }

  inline SignOutput& operator=(SignOutput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SignOutput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SignOutput* internal_default_instance() {
    return reinterpret_cast<const SignOutput*>(
               &_SignOutput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SignOutput* other);
  friend void swap(SignOutput& a, SignOutput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SignOutput* New() const final {
    return CreateMaybeMessage<SignOutput>(nullptr);
  }

  SignOutput* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SignOutput>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SignOutput& from);
  void MergeFrom(const SignOutput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SignOutput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string signature = 1;
  void clear_signature();
  static const int kSignatureFieldNumber = 1;
  const ::std::string& signature() const;
  void set_signature(const ::std::string& value);
  #if LANG_CXX11
  void set_signature(::std::string&& value);
  #endif
  void set_signature(const char* value);
  void set_signature(const char* value, size_t size);
  ::std::string* mutable_signature();
  ::std::string* release_signature();
  void set_allocated_signature(::std::string* signature);

  // @@protoc_insertion_point(class_scope:e2e_message.SignOutput)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr signature_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Signature_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SignInput

// string datas = 1;
inline void SignInput::clear_datas() {
  datas_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SignInput::datas() const {
  // @@protoc_insertion_point(field_get:e2e_message.SignInput.datas)
  return datas_.GetNoArena();
}
inline void SignInput::set_datas(const ::std::string& value) {
  
  datas_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:e2e_message.SignInput.datas)
}
#if LANG_CXX11
inline void SignInput::set_datas(::std::string&& value) {
  
  datas_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:e2e_message.SignInput.datas)
}
#endif
inline void SignInput::set_datas(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  datas_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:e2e_message.SignInput.datas)
}
inline void SignInput::set_datas(const char* value, size_t size) {
  
  datas_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:e2e_message.SignInput.datas)
}
inline ::std::string* SignInput::mutable_datas() {
  
  // @@protoc_insertion_point(field_mutable:e2e_message.SignInput.datas)
  return datas_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SignInput::release_datas() {
  // @@protoc_insertion_point(field_release:e2e_message.SignInput.datas)
  
  return datas_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SignInput::set_allocated_datas(::std::string* datas) {
  if (datas != nullptr) {
    
  } else {
    
  }
  datas_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), datas);
  // @@protoc_insertion_point(field_set_allocated:e2e_message.SignInput.datas)
}

// -------------------------------------------------------------------

// SignOutput

// string signature = 1;
inline void SignOutput::clear_signature() {
  signature_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SignOutput::signature() const {
  // @@protoc_insertion_point(field_get:e2e_message.SignOutput.signature)
  return signature_.GetNoArena();
}
inline void SignOutput::set_signature(const ::std::string& value) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:e2e_message.SignOutput.signature)
}
#if LANG_CXX11
inline void SignOutput::set_signature(::std::string&& value) {
  
  signature_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:e2e_message.SignOutput.signature)
}
#endif
inline void SignOutput::set_signature(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:e2e_message.SignOutput.signature)
}
inline void SignOutput::set_signature(const char* value, size_t size) {
  
  signature_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:e2e_message.SignOutput.signature)
}
inline ::std::string* SignOutput::mutable_signature() {
  
  // @@protoc_insertion_point(field_mutable:e2e_message.SignOutput.signature)
  return signature_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SignOutput::release_signature() {
  // @@protoc_insertion_point(field_release:e2e_message.SignOutput.signature)
  
  return signature_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SignOutput::set_allocated_signature(::std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  signature_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), signature);
  // @@protoc_insertion_point(field_set_allocated:e2e_message.SignOutput.signature)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace e2e_message

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_Signature_2eproto
